FROM golang:alpine as builder
RUN mkdir /build
ADD . /build/
WORKDIR /build
RUN go build -o main .

FROM alpine
ARG COMMIT_ID
ENV VERSION "1.0.0"
ENV COMMIT_ID "${COMMIT_ID}"

LABEL VERSION="1.0.0" \
    COMMIT_ID=${COMMIT_ID}

LABEL CLUSTER_80_NAME=service2

COPY --from=builder /build/main /app/
WORKDIR /app
CMD ["./main"]
EXPOSE 80